---
title: "ncaa-wp"
author: "Ethan Park"
date: "2023-12-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# for (year in seq(2016, 2002, -1)) {
#     print(paste0("Working on year: ", year))
#     write_csv(ncaa_teams(year), file = paste0("./data/teams/", year, "-1.csv"))
# }
```

```{r}
if (!requireNamespace('devtools', quietly = TRUE)){
  install.packages('devtools')
}
devtools::install_github(repo = "BillPetti/baseballr")

library(tidyverse)
library(baseballr)
library(stringr)
library(RCurl)
library(XML)
library(parallel)
library(fuzzyjoin)
```

```{r}
cl <- makeCluster(detectCores())
```


```{r Add Pitcher Functions}
retrieve_game_pbp <- function(game_info_url) {
  tryCatch({
    game_pbp <- ncaa_pbp(game_info_url = game_info_url)
    return(game_pbp)
  }, error = function(e) {
    return(NULL)
  })
}

parse_pitcher_data <- function(pitchers_df, top_bot) {
  pitchers_df <- pitchers_df %>%
    select(Player, App, IP) %>% 
    filter(App == "1") %>%
    mutate(IP = ifelse(IP == "", "0.0", IP)) %>% 
    separate(IP, into = c("inning", "outs"), sep = "\\.") %>% 
    mutate(
      inning_top_bot = top_bot,
      inning = as.numeric(inning),
      outs = as.numeric(gsub("[^0-9.]+", "", outs)),
      Player = str_trim(Player)
    ) %>% 
    rename(pitcher_name = Player) %>% 
    compute_end_inning_outs() %>% 
    rename(last_inning = inning, last_outs = outs)
  
  return(pitchers_df)
}

compute_end_inning_outs <- function(pitchers_df) {
  curr_inning <- ifelse(is.na(pitchers_df$inning[nrow(pitchers_df)]), 0, pitchers_df$inning[nrow(pitchers_df)])
  curr_outs <- ifelse(is.na(pitchers_df$outs[nrow(pitchers_df)]), 0, pitchers_df$outs[nrow(pitchers_df)])
  
  for (i in seq(nrow(pitchers_df) - 1, 1)) {
    if (i < 1) {break}
    curr_inning <- curr_inning + ifelse(!is.na(pitchers_df$inning[i]), pitchers_df$inning[i], 0)
    curr_outs <- curr_outs + ifelse(!is.na(pitchers_df$outs[i]), pitchers_df$outs[i], 0)
    
    if (curr_outs >= 3) {
      curr_inning <- curr_inning + 1
      curr_outs <- curr_outs %% 3
    }
    
    pitchers_df$inning[i] <- curr_inning
    pitchers_df$outs[i] <- curr_outs
  }
  return(pitchers_df)
}

fill_pitchers <- function(sample_game_data, pitcher_df) {
  i <- nrow(pitcher_df)
  j <- 1
  n <- nrow(sample_game_data)
  while (j <= n) {
    # If the NEXT pitcher did not make an out in their appearance (BAD OUTING), 
    # assign all of the PAs from this pitcher and the BAD OUTING pitcher to the 
    # BAD OUTING pitcher.
    # Rationale: Didn't protect against this edge case earlier. Possible with sub_fl.
    # Batters Faced (BF) data from NCAA is not perfect but could also inform a better approach. 
    if (i > 1 && 
        pitcher_df$last_inning[i] == pitcher_df$last_inning[i - 1] &&
        pitcher_df$last_outs[i] == pitcher_df$last_outs[i - 1]) {
      i <- i - 1
    }
    ############################################################################
    
    if (pitcher_df$last_inning[i] >= sample_game_data$inning[j]) {
      sample_game_data$pitcher_name[j] <- pitcher_df$pitcher_name[i]
    }
    else {
      outs <- pitcher_df$last_outs[i]
      while (j <= nrow(sample_game_data) && outs >= sample_game_data$outs_after[j]) {
        sample_game_data$pitcher_name[j] <- pitcher_df$pitcher_name[i]
        j <- j + 1 
      }
      i <- i - 1
      if (i >= 1) {
        sample_game_data$pitcher_name[j] <- pitcher_df$pitcher_name[i]
      }
    }
    j <- j + 1
  }
  
  return(slice(sample_game_data, 1:n))
}


add_pitchers_to_game_pbp <- function(game_pbp, game_info_url) {
  tryCatch({
    box_score = getURL(game_info_url) %>% 
      readHTMLTable(header = TRUE, skip.rows = 1) %>% 
      tail(2)
  }, error = function(e) {
    message(paste0("Failed on reading HTML Table from ", game_info_url, ". ", e))
    next
  })
  
  away_pitchers <- parse_pitcher_data(as.data.frame(box_score[[1]]), 'bot')
  home_pitchers <- parse_pitcher_data(as.data.frame(box_score[[2]]), 'top')
  
  game_pbp <- game_pbp %>% 
    mutate(X = row_number(),
           pitcher_name = NA)

  h <- game_pbp %>%
    filter(inning_top_bot == "top") %>%
    fill_pitchers(home_pitchers)  %>% 
    select(X, pitcher_name)
  
  a <- game_pbp %>%
    filter(inning_top_bot == "bot") %>%
    fill_pitchers(away_pitchers) %>% 
    select(X, pitcher_name)
  
  game_pbp <- game_pbp %>%
    left_join(h, by = "X", suffix = c("", "_h")) %>%
    mutate(
      pitcher_name = ifelse(is.na(pitcher_name), pitcher_name_h, pitcher_name),
    ) %>% 
    select(-pitcher_name_h) %>% 
    left_join(a, by = "X", suffix = c("", "_a")) %>%
    mutate(
      pitcher_name = ifelse(is.na(pitcher_name), pitcher_name_a, pitcher_name),
      pitcher_name = ifelse(is.na(pitcher_name), "", pitcher_name)
    ) %>%
    select(-pitcher_name_a, -X)
  
  return(game_pbp)
}
```

```{r Dave Miller PBP Parser Functions}
stripwhite <- function(x) gsub("\\s*$", "", gsub("^\\s*", "", x))

strip_punc <- function(x){
  x=stripwhite(x)
  x=ifelse(str_sub(x,-1)=='.',gsub("\\.", "", x),x)
  return(x)}

new_game=function(game_end){
  m = length(game_end)
  new_game=integer(m)
  new_game[1]=1
  for (i in 2:m){
    new_game[i]=game_end[i-1]
  }
  return(new_game)
}

r1_name = function(bat_text, bat_name, r1_text, r1_name, inn_end, game_end, sub_in, sub_out) {
  m = length(bat_text)
  r1_name = character(m)

  for (i in 2:m) {
    if (inn_end[i - 1] == 0 & game_end[i - 1] == 0) {
      r1_name[i] = case_when(
        sub_out[i - 1] != '' & sub_out[i - 1] == stripwhite(r1_name[i - 1]) ~ sub_in[i - 1],

        (str_detect(bat_text[i - 1], '(singled|walked|hit by pitch|reached|error)') == TRUE) &
          (str_detect(bat_text[i - 1], '(doubled|tripled|homered|advanced|scored|out|stole)') == FALSE) ~ bat_name[i - 1],

        (str_detect(bat_text[i - 1], '(reached first)') == TRUE) &
          (str_detect(bat_text[i - 1], '(struck out)') == TRUE) ~ bat_name[i - 1],

        (r1_text[i - 1] == '' | (str_detect(r1_text[i - 1], '(advanced to second|stole second|advanced to third|stole third|scored|out)') == FALSE)) & (str_detect(bat_text[i - 1], '(double play|advanced to second|stole second|advanced to third|stole third|scored|caught stealing|picked off|homered)') == FALSE) ~ r1_name[i - 1],

        (str_detect(bat_text[i - 1], '(singled|doubled|tripled|advanced to second|stole second|advanced to third|stole third|scored|homered|out at second c to)') == FALSE) & (str_detect(r1_text[i - 1], '(advanced to third|stole third|scored|out at third)') == TRUE) & stripwhite(gsub('((advanced to second|stole second|stole third|advanced to third|scored|out).*$)', '', r1_text[i - 1])) != stripwhite(gsub('((singled|reached).*$)', '', r1_name[i - 1])) ~ r1_name[i - 1],
        r1_text[i - 1] == '' & stripwhite(gsub('((advanced to second|stole second|stole third|advanced to third|scored|out|failed|Failed|picked off).*$)', '', bat_text[i - 1])) != stripwhite(r1_name[i - 1]) ~ r1_name[i - 1]
      )
    }
  }
  return(stripwhite(r1_name))
}



r2_name = function(bat_text, bat_name, r1_text, r1_name, r2_text, r2_name,  inn_end, game_end, sub_in, sub_out){
  m=length(bat_text)
  r2_name= character(m)
  for (i in 2:m){
    if (inn_end[i-1]==0 & game_end[i-1]==0){
      r2_name[i]=case_when(
        sub_out[i-1]!=''&sub_out[i-1]==stripwhite(r2_name[i-1])~sub_in[i-1],
        ((str_detect(bat_text[i-1], '(doubled|advanced to second|stole second)') == TRUE) & (str_detect(bat_text[i-1], '(advanced to third|scored|out|stole third)') == FALSE)) ~ stripwhite(gsub('((doubled|advanced to second|stole second).*$)', '', bat_text[i-1])),
        ((str_detect(r1_text[i-1], '(advanced to second|stole second)') == TRUE) & (str_detect(r1_text[i-1], '(advanced to third|scored|out|stole third)') == FALSE)) ~ stripwhite(gsub('((advanced to second|stole second).*$)', '', r1_text[i-1])),
        r2_text[i-1]=='' & stripwhite(gsub('((stole third|advanced to third|scored|out).*$)', '', r1_text[i-1]))!=stripwhite(r2_name[i-1]) & (str_detect(bat_text[i-1], '(advanced to third|stole third|scored|picked off|caught stealing)') == FALSE) ~ r2_name[i-1],
        r2_text[i-1]=='' & stripwhite(gsub('((out on the play).*$)', '', r1_text[i-1]))!=stripwhite(r2_name[i-1]) & (str_detect(bat_text[i-1], '(double play)') == TRUE) ~ r2_name[i-1],
        r1_text[i-1]=='' & (str_detect(bat_text[i-1], '(stole third|advanced to third|scored|picked off|homered|caught stealing)') == FALSE) ~ r2_name[i-1],
        sub_out[i-1]!=''&sub_out[i-1]==stripwhite(r2_name[i-1])~sub_in[i-1]
      )
      r2_name[i]=stripwhite(gsub('((singled|reached).*$)', '', r2_name[i]))
    }
  }
  return(stripwhite(r2_name))
}


r3_name = function(bat_text, bat_name, r1_text, r1_name, r2_text, r2_name, r3_text, r3_name, inn_end, game_end, sub_in, sub_out){
  m=length(bat_text)
  r3_name= character(m)
  for (i in 2:m){
    if (inn_end[i-1]==0 & game_end[i-1]==0){
      r3_name[i]=case_when(
        sub_out[i-1]!=''&sub_out[i-1]==stripwhite(r3_name[i-1])~sub_in[i-1],
        ((str_detect(bat_text[i-1], '(tripled|advanced to third|stole third)') == TRUE) & (str_detect(bat_text[i-1], '(scored|out)') == FALSE)) ~ stripwhite(gsub('((tripled|advanced to third|stole third).*$)', '', bat_text[i-1])),
        ((str_detect(r1_text[i-1], '(advanced to third|stole third)') == TRUE) & (str_detect(r1_text[i-1], '(scored|out)') == FALSE)) ~ stripwhite(gsub('((advanced to third|stole third).*$)', '', r1_text[i-1])),
        ((str_detect(r2_text[i-1], '(advanced to third|stole third)') == TRUE) & (str_detect(r2_text[i-1], '(scored|out)') == FALSE)) ~ stripwhite(gsub('((advanced to third|stole third).*$)', '', r2_text[i-1])),
        r1_text[i-1]=='' & (str_detect(bat_text[i-1], '(scored|stole home|homered)') == FALSE) ~ r3_name[i-1],
        r2_text[i-1]=='' & stripwhite(gsub('((scored|stole home|out).*$)', '', r1_text[i-1]))!=stripwhite(r3_name[i-1]) & (str_detect(bat_text[i-1], '(scored|stole home)') == FALSE) ~ r3_name[i-1],
        r3_text[i-1]=='' & (str_detect(r2_text[i-1], '(scored|stole home|out)') == FALSE) & (str_detect(r1_text[i-1], '(scored|stole home|out)') == FALSE) & (str_detect(bat_text[i-1], '(scored|stole home)') == FALSE) ~ r3_name[i-1])
      r3_name[i]=stripwhite(gsub('((singled|doubled|reached|advanced|stole|failed|Failed|picked off).*$)', '', r3_name[i]))
    }
  }
  return(stripwhite(r3_name))
}

inn_end = function(top_inn){
  m=length(top_inn)
  inn_end=integer(m)
  for (i in 1:(m-1)){
    inn_end[i]=ifelse(top_inn[i]!=top_inn[i+1], 1,0)
  }
  inn_end[m]=1
  return(inn_end)
}

game_end = function(game_id){
  m=length(game_id)
  game_end=integer(m)
  for (i in 2:m){
    if (game_id[i]!=game_id[i-1]){
      game_end[i-1]=1
    }
    game_end[m]=1
  }
  return(game_end)
}

new_inn=function(inn_end){
  m = length(inn_end)
  new_inn=integer(m)
  new_inn[1]=1
  for (i in 2:m){
    new_inn[i]=inn_end[i-1]
  }
  return(new_inn)
}

outs_before= function(outs_on_play, new_game, new_inn){
  m=length(outs_on_play)
  inn_outs=integer(m)
  for (i in 2:m){
    if (new_game[i]==0 & new_inn[i]==0){
      inn_outs[i]=((inn_outs[i-1]+outs_on_play[i-1]) %% 3)
    }
  }
  return(inn_outs)
}
```

```{r}
years <- seq(2020, 2002, by=-1)
divisions <- c(1
               # , 2
               # , 3
)

write_path <- "./data/raw-pbps/"
for (division in divisions) {
  for (year in years) {
    print(paste0('Starting ', year, "-", division))
    read_path <- paste0("./data/teams/", year, "-", division, ".csv")
    teams <- read_csv(read_path, col_select = c("team_id",	"team_name"),
                        col_types = list(col_number(), col_character()))
    
    files <- list.files(path = paste0(write_path, year, "-", division), pattern = "\\.csv$", full.names = TRUE)
    completed_team_ids <- unique(as.numeric(gsub("^(\\d+)-.*\\.csv$", "\\1", basename(files))))
    
    teams <- teams %>% 
      filter(!(team_id %in% completed_team_ids))
      # filter(team_id == 196)

    for (team_id in teams$team_id) {
      skip_to_next <- FALSE
      tryCatch({
        team_schedule <- ncaa_schedule_info(team_id, year)
      }, error = function(e_schedule_info) {
        skip_to_next <- TRUE
      })
      if (skip_to_next) { next }
      if (nrow(team_schedule) == 0) { next }
      
      filtered_team_schedule <- team_schedule %>% 
          filter(home_team_id == team_id) %>% 
          select(game_info_url, away_team_id, year)
      
      n_games <- nrow(filtered_team_schedule)
      for (i in 1:n_games) {
        game_info_url <- filtered_team_schedule$game_info_url[i]
        game_pbp <- retrieve_game_pbp(game_info_url)
        away_team_id <- filtered_team_schedule$away_team_id[i]
        if (!is.null(game_pbp)) {
          tryCatch({
            home_roster <- ncaa_roster(team_id, year)
            away_roster <- ncaa_roster(away_team_id, year)
          }, error = function(e_roster) {
            skip_to_next <- TRUE
          })
          if (skip_to_next) { next }
  
          # Set away, home at game-level
          game_pbp <- game_pbp %>%
            rename(away_team = batting,
                   home_team = fielding) %>%
            mutate(away_team = game_pbp$batting[1],
                   home_team = game_pbp$fielding[1])
          
          game_pbp <- game_pbp %>%
              separate(score, into = c("away_score_after", 
                                       "home_score_after"), sep = "-") %>%
              mutate(
                away_score_before = lag(as.numeric(away_score_after), default = 0),
                home_score_before = lag(as.numeric(home_score_after), default = 0),
              )
          
          game_pbp <- tryCatch({
              game_pbp %>%
              mutate(
                home_team_id = team_id,
                away_team_id = away_team_id,
                
                inning = as.numeric(inning),

                # Create flag for substitution such as pinch hitter/runner
                sub_fl = case_when(
                  str_detect(description, '(singled|doubled|tripled|homered|walked|reached|struck out|grounded|flied|lined|popped|hit|infield fly|out|double play|triple play)') == TRUE &
                    str_detect(description, c('pinch hit')) == FALSE ~ 0,

                  str_detect(description, c('to (p|c|1b|2b|3b|ss|lf|rf|cf|dh)')) == TRUE ~ 1,

                  str_detect(description, c('pinch hit')) == TRUE ~ 1,

                  str_detect(description, c('pinch ran')) == TRUE ~ 1,

                  TRUE ~ 0
                ),

                # Split the text up
                bat_text=gsub('(;|3a|:).*$','', description),

                r1_text = case_when(
                  str_detect(description, '(;|3a|:)') == TRUE ~ stripwhite(gsub('^.*?(;|3a|:)', '', description)),
                  TRUE ~ ''
                ),
                r2_text = case_when(
                  str_detect(r1_text, '(;|3a|:)') == TRUE ~ stripwhite(gsub('^.*?(;|3a|:)', '', r1_text)),
                  TRUE ~ ''
                ),
                r3_text = case_when(
                  str_detect(r2_text, '(;|3a|:)') == TRUE ~ stripwhite(gsub('^.*?(;|3a|:)', '', r2_text)),
                  TRUE ~ ''
                ),
                r2_text = stripwhite(gsub('(;|3a|:).*$', '', r2_text)),
                r1_text = stripwhite(gsub('(;|3a|:).*$', '', r1_text)),

                top_inning = ifelse(inning_top_bot == 'top', 1, 0),

                # (Retrosheet) Event codes
                event_cd=case_when(
                  sub_fl==1 ~ 1,
                  str_sub(stripwhite(description),1,1)=='(' ~ 1,
                  str_detect(description, '(hitting out of turn| for |
                             No play|halted|delay|postponed|ejected|suspended|
                             coach|sunny|review|challenged|HC|\\*\\*)') == TRUE ~ 1,
                  str_detect(description,'struck out') == TRUE ~ 3,
                  str_detect(description,'stole') == TRUE ~ 4,
                  (str_detect(description,'(caught stealing|out at second c to|out
                              at third c to)') == TRUE) &
                    (str_detect(description,'(bunt|grounded)') == FALSE) ~ 6,
                  str_detect(description,'picked off') == TRUE ~ 8,
                  str_detect(description,'wild pitch') == TRUE ~ 9,
                  str_detect(description,'passed ball') == TRUE ~ 10,
                  str_detect(description,'balk') == TRUE ~ 11,
                  str_detect(description,'Dropped foul') == TRUE ~ 13,
                  str_detect(description,'walked') == TRUE ~ 14,
                  str_detect(description,'hit by pitch') == TRUE ~ 16,
                  str_detect(description,'interference') == TRUE ~ 17,
                  str_detect(description,'error') == TRUE ~ 18,
                  str_detect(description,'muffed') == TRUE ~ 18,
                  str_detect(description,'dropped') == TRUE ~ 18,
                  str_detect(description,'fielder\'s choice') == TRUE ~ 19,
                  str_detect(description,'singled') == TRUE ~ 20,
                  str_detect(description,'doubled') == TRUE ~ 21,
                  str_detect(description,'tripled') == TRUE ~ 22,
                  str_detect(description,'homered') == TRUE ~ 23,
                  str_detect(description, '(flied out|grounded out|popped|fouled out|lined out| infield fly|double play|triple play|out at (first|second|third|home))') == TRUE ~ 2,
                  str_detect(description, 'advanced') == TRUE ~ 12,
                  TRUE ~ 0),


                # Bat name
                bat_name= case_when(
                  event_cd %in% c(0,1)~'',
                  str_detect(bat_text, '(Batter|Runner\'s interference)')==TRUE ~'',
                  str_detect(bat_text, '(walked|singled|doubled|tripled|reached|struck out|grounded out)')==FALSE &
                    str_detect(bat_text, '(advanced|caught stealing|stole|picked off|out at (first|second|third|home)|tagged out)')==TRUE ~ '',
                  str_detect(bat_text, '(singled|doubled|tripled|homered|walked|hit by|error|reached|struck out|grounded|flied|lined|popped|hit | out |fouled out|pinch hit|infield fly|intentionally walked|was intentionally walked|fouled into double play)')==TRUE ~ gsub('((singled|doubled|tripled|homered|walked|hit by|error|reached|struck out|grounded|flied|lined|popped|hit | out |fouled out|pinch hit|infield fly|intentionally walked|was intentionally walked|fouled into double play).*$)', '', bat_text),
                  str_detect(stripwhite(r1_text), 'caught stealing  c to (2b|3b), double play.')==TRUE ~ bat_text,
                  TRUE ~ ''),

                #  Sub in
                sub_in = case_when(
                  sub_fl == 1 & str_detect(bat_text, 'to (p|c|1b|2b|3b|ss|lf|rf|cf|dh)') == TRUE ~
                    stripwhite(gsub('(to (p|c|1b|2b|3b|ss|lf|rf|cf|dh).*$)', '', bat_text)),

                  sub_fl == 1 & str_detect(bat_text, 'pinch ran for') == TRUE ~
                    stripwhite(gsub('pinch ran for.*$', '', bat_text)),

                  sub_fl == 1 & str_detect(bat_text, 'pinch hit for') == TRUE ~
                    stripwhite(gsub('pinch hit for.*$', '', bat_text)),

                  TRUE ~ '',
                ),

                # Sub out
                sub_out = case_when(
                  sub_fl == 1 & str_detect(bat_text, 'to (p|c|1b|2b|3b|ss|lf|rf|cf|dh) for') == TRUE ~
                    gsub('^.*to (p|c|1b|2b|3b|ss|lf|rf|cf|dh) for', '', bat_text),

                  sub_fl == 1 & str_detect(bat_text, 'pinch ran for') == TRUE ~
                    gsub('^.*pinch ran for', '', bat_text),

                  sub_fl == 1 & str_detect(bat_text, 'pinch hit') == TRUE ~
                    gsub('^.*pinch hit for', '', bat_text),

                  TRUE ~ ''
                ),
                sub_out = strip_punc(sub_out),

                game_end = game_end(game_pbp_id),
                # New game
                new_game=new_game(game_end),

                # End of inning
                inn_end = inn_end(top_inning),

                # Runner names
                r1_name=r1_name(bat_text, bat_name, r1_text, r1_name, inn_end, game_end, sub_in, sub_out),
                r2_name =r2_name(bat_text, bat_name, r1_text, r1_name, r2_text, r2_name, inn_end, game_end, sub_in, sub_out),
                r3_name =r3_name(bat_text, bat_name, r1_text, r1_name, r2_text, r2_name, r3_text, r3_name, inn_end, game_end, sub_in, sub_out),
                # Clean runner names
                r1_name=replace(r1_name,is.na(r1_name),''),
                r2_name=replace(r2_name,is.na(r2_name),''),
                r3_name=replace(r3_name,is.na(r3_name),''),

                # Fix repeat bat names
                bat_name=case_when(
                  bat_name!='' & stripwhite(bat_name)==stripwhite(r1_name)~ '',
                  bat_name!='' & stripwhite(bat_name)==stripwhite(r2_name)~ '',
                  bat_name!='' & stripwhite(bat_name)==stripwhite(r3_name)~ '',
                  TRUE ~ bat_name),

                outs_on_play=case_when(
                  event_cd %in% c(0,1) ~ 0,
                  str_count(bat_text, 'triple play') == 1 ~ 3,
                  str_count(bat_text, 'double play') == 1 ~ 2,
                  (str_detect(bat_text, '( out|popped)') == TRUE) &  (str_detect(bat_text, '(reached)') == TRUE) ~ 0,
                  # 1 out
                  ((str_detect(bat_text, '( out |popped|infield fly)') == TRUE) & (str_detect(r1_text, '( out |popped)')==FALSE) & (str_detect(r2_text, '( out |popped)')==FALSE) &(str_detect(r3_text, '( out |popped)')==FALSE)) |
                    ((str_detect(bat_text, '( out |popped|infield fly)') == FALSE) & (str_detect(r1_text, '( out |popped)')==TRUE) & (str_detect(r2_text, '( out |popped)')==FALSE) &(str_detect(r3_text, '( out |popped)')==FALSE)) |
                    ((str_detect(bat_text, '( out |popped|infield fly)') == FALSE) & (str_detect(r1_text, '( out |popped)')==FALSE) & (str_detect(r2_text, '( out |popped)')==TRUE) &(str_detect(r3_text, '( out |popped)')==FALSE)) |
                    ((str_detect(bat_text, '( out |popped|infield fly)') == FALSE) & (str_detect(r1_text, '( out |popped)')==FALSE) & (str_detect(r2_text, '( out |popped)')==FALSE) &(str_detect(r3_text, '( out |popped)')==TRUE)) ~ 1,
                  #  2 outs
                  ((str_detect(bat_text, '( out |popped|infield fly)') == TRUE) & (str_detect(r1_text, '( out |popped)')==TRUE) & (str_detect(r2_text, '( out |popped)')==FALSE) &(str_detect(r3_text, '( out |popped)')==FALSE)) |
                    ((str_detect(bat_text, '( out |popped|infield fly)') == TRUE) & (str_detect(r1_text, '( out |popped)')==FALSE) & (str_detect(r2_text, '( out |popped)')==TRUE) &(str_detect(r3_text, '( out |popped)')==FALSE)) |
                    ((str_detect(bat_text, '( out |popped|infield fly)') == TRUE) & (str_detect(r1_text, '( out |popped)')==FALSE) & (str_detect(r2_text, '( out |popped)')==FALSE) &(str_detect(r3_text, '( out |popped)')==TRUE)) |
                    ((str_detect(bat_text, '( out |popped|infield fly)') == FALSE) & (str_detect(r1_text, '( out |popped)')==TRUE) & (str_detect(r2_text, '( out |popped)')==TRUE) &(str_detect(r3_text, '( out |popped)')==FALSE)) |
                    ((str_detect(bat_text, '( out |popped|infield fly)') == FALSE) & (str_detect(r1_text, '( out |popped)')==TRUE) & (str_detect(r2_text, '( out |popped)')==FALSE) &(str_detect(r3_text, '( out |popped)')==TRUE)) |
                    ((str_detect(bat_text, '( out |popped|infield fly)') == FALSE) & (str_detect(r1_text, '( out |popped)')==FALSE) & (str_detect(r2_text, '( out |popped)')==TRUE) &(str_detect(r3_text, '( out |popped)')==TRUE)) ~ 2,
                  # 3 outs
                  ((str_detect(bat_text, '( out |popped|infield fly)') == TRUE) & (str_detect(r1_text, '( out |popped)')==TRUE) & (str_detect(r2_text, '( out |popped)')==TRUE) &(str_detect(r3_text, '( out |popped)')==FALSE)) |
                    ((str_detect(bat_text, '( out |popped|infield fly)') == TRUE) & (str_detect(r1_text, '( out |popped)')==FALSE) & (str_detect(r2_text, '( out |popped)')==TRUE) &(str_detect(r3_text, '( out |popped)')==TRUE)) |
                    ((str_detect(bat_text, '( out |popped|infield fly)') == TRUE) & (str_detect(r1_text, '( out |popped)')==TRUE) & (str_detect(r2_text, '( out |popped)')==FALSE) &(str_detect(r3_text, '( out |popped)')==TRUE)) |
                    ((str_detect(bat_text, '( out |popped)') == FALSE) & (str_detect(r1_text, '( out |popped)')==TRUE) & (str_detect(r2_text, '( out |popped)')==TRUE) &(str_detect(r3_text, '( out |popped)')==TRUE)) ~ 3,
                  TRUE ~ 0),

                # New inning
                new_inn=new_inn(inn_end),

                # Outs before
                outs_before=outs_before(outs_on_play, new_game, new_inn),
                # Outs after
                outs_after=outs_before+outs_on_play,

                # Base code
                base_cd_before=case_when(
                  stripwhite(r1_name)!='' & r2_name=='' & r3_name=='' ~ 1,
                  r1_name=='' & r2_name!='' & r3_name=='' ~ 2,
                  r1_name!='' & r2_name!='' & r3_name=='' ~ 3,
                  r1_name=='' & r2_name=='' & r3_name!='' ~ 4,
                  r1_name!='' & r2_name=='' & r3_name!='' ~ 5,
                  r1_name=='' & r2_name!='' & r3_name!='' ~ 6,
                  r1_name!='' & r2_name!='' & r3_name!='' ~ 7,
                  TRUE~0),

                base_cd_after = lead(as.numeric(base_cd_before), default = 0),
              )
            }, error = function(e) {
                cat("Error occurred while processing game:", i, "for team:", team_id, "\n")
                return(NULL)
            })
          
          if (is.null(game_pbp)) {
            next
          }
          
          game_pbp <- game_pbp %>% 
            select(year, home_team, home_team_id, away_team, away_team_id, inning, inning_top_bot, top_inning, event_cd, bat_name,
                   home_score_before, home_score_after, away_score_before,
                   away_score_after, outs_before, outs_after, base_cd_before,
                   base_cd_after, game_end, new_game)
    
          last_row <- tail(game_pbp, 1)
          won_last_row <- ifelse(as.numeric(last_row$home_score_after) > as.numeric(last_row$away_score_after), 1, 0)
          
          game_pbp <- game_pbp %>%
            filter(event_cd != 0 & event_cd != 1 & inning < 10) %>%
            mutate(won = won_last_row)
          
          tryCatch({
            game_pbp <- add_pitchers_to_game_pbp(game_pbp, game_info_url) %>% 
              mutate(i = row_number()) %>% 
              stringdist_join(select(home_roster, h_player_name = player_name, h_bat_id = player_id), 
                              by = c(bat_name = "h_player_name"),
                              max_dist = 50,
                              method = "jw",
                              mode = "left",
                              ignore_case = TRUE,
                              distance_col = "h_dist") %>% 
              group_by(i) %>% 
              mutate(h_rank = row_number(h_dist)) %>% 
              filter(h_rank == 1) %>% 
              stringdist_join(select(away_roster, a_player_name = player_name, a_bat_id = player_id), 
                              by = c(bat_name = "a_player_name"),
                              max_dist = 50,
                              method = "jw",
                              mode = "left",
                              ignore_case = TRUE,
                              distance_col = "a_dist") %>% 
              group_by(i) %>% 
              mutate(a_rank = row_number(a_dist)) %>% 
              filter(a_rank == 1) %>% 
              mutate(bat_id = ifelse(a_dist < h_dist, a_bat_id, h_bat_id),
                     fuzzy_matched_bat_name = ifelse(a_dist < h_dist, a_player_name, h_player_name)) %>% 
              select(-h_player_name, -h_bat_id, -h_rank, -h_dist, -a_player_name, -a_bat_id, -a_rank, -a_dist) %>% 
              stringdist_join(select(home_roster, h_player_name = player_name, h_pitcher_id = player_id), 
                              by = c(pitcher_name = "h_player_name"),
                              max_dist = 50,
                              method = "jw",
                              mode = "left",
                              ignore_case = TRUE,
                              distance_col = "h_dist") %>% 
              group_by(i) %>% 
              mutate(h_rank = row_number(h_dist)) %>% 
              filter(h_rank == 1) %>% 
              stringdist_join(select(away_roster, a_player_name = player_name, a_pitcher_id = player_id), 
                              by = c(pitcher_name = "a_player_name"),
                              max_dist = 50,
                              method = "jw",
                              mode = "left",
                              ignore_case = TRUE,
                              distance_col = "a_dist") %>% 
              group_by(i) %>% 
              mutate(a_rank = row_number(a_dist)) %>% 
              filter(a_rank == 1) %>% 
              ungroup() %>%
              mutate(pitcher_id = ifelse(a_dist < h_dist, a_pitcher_id, h_pitcher_id),
                     fuzzy_matched_pitcher_name = ifelse(a_dist < h_dist, a_player_name, h_player_name)) %>% 
              select(-h_player_name, -h_pitcher_id, -h_rank, -h_dist, -a_player_name, -a_pitcher_id, -a_rank, -a_dist) %>%
              mutate(fuzzy_matched_bat_name = ifelse(is.na(bat_name) | bat_name == "", NaN, fuzzy_matched_bat_name),
                     bat_id = ifelse(is.na(bat_name) | bat_name == "", NaN, bat_id)) %>% 
              select(year, home_team, home_team_id, away_team, away_team_id, inning, inning_top_bot, top_inning, event_cd, bat_name, fuzzy_matched_bat_name, bat_id, pitcher_name, fuzzy_matched_pitcher_name, pitcher_id, home_score_before, home_score_after, away_score_before, away_score_after, outs_before, outs_after, base_cd_before, base_cd_after, game_end, new_game, won)
            
            write_csv(game_pbp, file = paste0(write_path, year, "-1/", team_id, "-", i, ".csv"))
            print(paste0("Completed Team ID: ", team_id, ", in ", year, " game: ", i, " / ", n_games))
          }, error = function(e_add_pitchers) {
            message(paste0("Failed to add pitchers on ", i, " with error", e_add_pitchers, ". Continuing."))
          })
        }
        Sys.sleep(0.25)
      }
    }
  }
}
```






